# Example docker-compose.override.yml for LibreChat integration
version: '3.8'

services:
  # GitLab MCP Server
  gitlab-mcp:
    build:
      context: ./gitlab-mcp
      dockerfile: Dockerfile.mcp-gitlab
    container_name: gitlab-mcp-server
    environment:
      - GITLAB_URL=${GITLAB_URL:-https://gitlab.com}
      - GITLAB_AUTH_MODE=${GITLAB_AUTH_MODE:-hybrid}
      - GITLAB_SHARED_ACCESS_TOKEN=${GITLAB_SHARED_ACCESS_TOKEN:-}
      - GITLAB_MAX_PAGE_SIZE=${GITLAB_MAX_PAGE_SIZE:-50}
      - GITLAB_TIMEOUT=${GITLAB_TIMEOUT:-30000}
    restart: unless-stopped
    networks:
      - librechat-network
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('GitLab MCP Server is healthy')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  librechat-network:
    external: true